#! /usr/bin/env python

from MultiDarkHydra import *

snList=  n.array(glob.glob("/lustre/jcomparat/MultiDark/MD_1.0Gpc_Rockstar/snapshots/out*.list.bz2"))

box = MultiDarkSimulation(Lbox=1000.0 , boxDir = "MD_1.0Gpc",snl =snList )

for ii in n.arange(len(box.snl)):
	box.writePositionCatalog(ii, vmin=65)


