#! /usr/bin/env python

from MultiDarkHydra import *

snList=  n.array(glob.glob("/lustre/jcomparat/MultiDark/MD_2.5Gpc_Rockstar/snapshots/out*p.list.bz2"))

box = MultiDarkSimulation(Lbox=2500.0 , boxDir = "MD_2.5Gpc",snl =snList )

for ii in n.arange(len(box.snl)):
	box.writePositionCatalog(ii, vmin=65)


